// Barnsley Fern - Ariadne's first wing
// Iterated Function System using probabilistic affine transformations
// Generates organic natural forms through random transformation selection
import type { ToolPlugin } from "../manager";

interface BarnsleyFernArgs {
  points?: number;
  width?: number;
  height?: number;
  symbol?: string;
}

interface FernPoint {
  x: number;
  y: number;
}

interface IFSTransform {
  a: number;
  b: number;
  c: number;
  d: number;
  e: number;
  f: number;
  w: number;
}

// Barnsley Fern IFS transformations
// Each transformation: x' = ax + by + e, y' = cx + dy + f
// With probability weight w
const IFS_TRANSFORMATIONS: IFSTransform[] = [
  // f1: Stem (1%)
  { a: 0.0, b: 0.0, c: 0.0, d: 0.16, e: 0.0, f: 0.0, w: 0.01 },
  // f2: Successive smaller leaflets (85%)
  { a: 0.85, b: 0.04, c: -0.04, d: 0.85, e: 0.0, f: 1.6, w: 0.85 },
  // f3: Left successively smaller leaflets (7%)
  { a: 0.2, b: -0.26, c: 0.23, d: 0.22, e: 0.0, f: 1.6, w: 0.07 },
  // f4: Right successively smaller leaflets (7%)
  { a: -0.15, b: 0.28, c: 0.26, d: 0.24, e: 0.0, f: 0.44, w: 0.07 },
];

function generateFernPoints(pointCount: number): FernPoint[] {
  const points: FernPoint[] = [];
  let x = 0.0;
  let y = 0.0;

  // Accumulate cumulative probabilities for selection
  const cumWeights: number[] = [];
  let cumSum = 0;
  for (const t of IFS_TRANSFORMATIONS) {
    cumSum += t.w;
    cumWeights.push(cumSum);
  }

  // Generate points using chaos game
  for (let i = 0; i < pointCount; i++) {
    const r = Math.random();
    
    // Select transformation based on probability weight
    let selected = IFS_TRANSFORMATIONS[0]!;
    for (let j = 0; j < cumWeights.length; j++) {
      if (r <= cumWeights[j]!) {
        selected = IFS_TRANSFORMATIONS[j]!;
        break;
      }
    }

    // Apply affine transformation
    const nx = selected.a * x + selected.b * y + selected.e;
    const ny = selected.c * x + selected.d * y + selected.f;
    
    x = nx;
    y = ny;

    points.push({ x, y });
  }

  return points;
}

function renderFern(points: FernPoint[], width: number, height: number, symbol: string): string {
  // Find bounds
  const xs = points.map(p => p.x);
  const ys = points.map(p => p.y);
  const minX = Math.min(...xs);
  const maxX = Math.max(...xs);
  const minY = Math.min(...ys);
  const maxY = Math.max(...ys);

  // Scale to fit with margin
  const xScale = (width - 4) / (maxX - minX || 1);
  const yScale = (height - 2) / (maxY - minY || 1);
  const scale = Math.min(xScale, yScale);

  // Center
  const xOffset = (width - (maxX - minX) * scale) / 2 - minX * scale;
  const yOffset = (height - (maxY - minY) * scale) / 2 - minY * scale;

  // Create grid
  const grid: string[][] = [];
  for (let y = 0; y < height; y++) {
    grid[y] = [];
    for (let x = 0; x < width; x++) {
      grid[y]![x] = ' ';
    }
  }

  // Plot points (flip Y since ASCII has 0 at top)
  for (const p of points) {
    const px = Math.floor(p.x * scale + xOffset);
    const py = height - 1 - Math.floor(p.y * scale + yOffset);
    if (px >= 0 && px < width && py >= 0 && py < height) {
      grid[py]![px] = symbol;
    }
  }

  // Build output
  const lines: string[] = [];
  for (let y = 0; y < height; y++) {
    lines.push(grid[y]!.join(''));
  }

  return lines.join('\n');
}

// Main function to run the IFS
async function runIFS(args: BarnsleyFernArgs): Promise<string> {
  const points = args.points ?? 10000;
  const width = args.width ?? 80;
  const height = args.height ?? 40;
  const symbol = args.symbol ?? '@';

  // Generate fern points
  const fernPoints = generateFernPoints(points);

  // Render
  const start = Date.now();
  const rendered = renderFern(fernPoints, width, height, symbol);
  const renderTime = Date.now() - start;

  // Calculate stats
  const xs = fernPoints.map(p => p.x);
  const ys = fernPoints.map(p => p.y);
  const minX = Math.min(...xs);
  const maxX = Math.max(...xs);
  const minY = Math.min(...ys);
  const maxY = Math.max(...ys);

  return `=== Barnsley Fern ===
IFS with ${IFS_TRANSFORMATIONS.length} affine transformations
Points: ${points.toLocaleString()}, Render: ${width}x${height}
Bounds: X[${minX.toFixed(2)}, ${maxX.toFixed(2)}] Y[${minY.toFixed(2)}, ${maxY.toFixed(2)}]
Render time: ${renderTime}ms

'.~-=+@%#${rendered}

Generated by Ariadne
IFS: Probabilistic affine transformations producing organic forms`;
}

// Tool definition
export const barnsleyFernPlugin: ToolPlugin = {
  definition: {
    type: "function",
    function: {
      name: "barnsleyfern",
      description: "Generate a Barnsley Fern using Iterated Function Systems (IFS) - probabilistic fractal generation",
      parameters: {
        type: "object",
        properties: {
          points: { type: "number", description: "Number of points to generate (default: 10000)" },
          width: { type: "number", description: "Canvas width in characters (default: 80)" },
          height: { type: "number", description: "Canvas height in characters (default: 40)" },
          symbol: { type: "string", description: "Character to use for rendering (default: '@')" }
        }
      }
    }
  },
  execute: runIFS
};
