import { describe, it, expect } from "vitest";
import { barnsleyFernPlugin } from "./barnsleyfern";

describe("BarnsleyFern Plugin", () => {
  describe("IFS Generation", () => {
    it("should generate output with default parameters", async () => {
      const result = await barnsleyFernPlugin.execute({});
      
      expect(result).toContain("=== Barnsley Fern ===");
      expect(result).toContain("IFS with 4 affine transformations");
      expect(result).toContain("Points:");
      expect(result).toContain("Generated by Ariadne");
    });

    it("should use custom point count", async () => {
      const result = await barnsleyFernPlugin.execute({ points: 100 });
      
      expect(result).toContain("Points: 100");
    });

    it("should use custom width and height", async () => {
      const result = await barnsleyFernPlugin.execute({ 
        width: 40, 
        height: 20 
      });
      
      expect(result).toContain("Render:");
      expect(result).toContain("40");
      expect(result).toContain("20");
    });

    it("should use custom symbol", async () => {
      const result = await barnsleyFernPlugin.execute({ 
        points: 1000,
        symbol: "F"
      });
      
      expect(result).toContain("F");
    });

    it("should generate fern pattern with proper probabilities", async () => {
      const result1 = await barnsleyFernPlugin.execute({ points: 500 });
      const result2 = await barnsleyFernPlugin.execute({ points: 500 });
      
      expect(result1).toContain("Barnsley Fern");
      expect(result2).toContain("Barnsley Fern");
      
      expect(result1).toMatch(/Bounds: X\[-?\d+\.\d+, -?\d+\.\d+\] Y/);
      expect(result2).toMatch(/Bounds: X\[-?\d+\.\d+, -?\d+\.\d+\] Y/);
    });

    it("should handle large point counts", async () => {
      const result = await barnsleyFernPlugin.execute({ points: 50000 });
      
      expect(result).toContain("Points: 50,000");
      expect(result).toContain("Render time:");
    });

    it("should handle small point counts", async () => {
      const result = await barnsleyFernPlugin.execute({ points: 10 });
      
      expect(result).toContain("Points: 10");
    });

    it("should maintain fern characteristics", async () => {
      const result = await barnsleyFernPlugin.execute({ points: 1000 });
      
      const lines = result.split('\n');
      const contentLines = lines.filter((l: string) => l.trim().length > 0);
      
      expect(contentLines.length).toBeGreaterThan(5);
      expect(result).toMatch(/Ariadne/);
      expect(result).toMatch(/affine transformations/);
      expect(result).toMatch(/Probabilistic/);
    });
  });

  describe("Plugin Metadata", () => {
    it("should have correct plugin name", () => {
      expect(barnsleyFernPlugin.definition.function.name).toBe("barnsleyfern");
    });

    it("should have description", () => {
      expect(barnsleyFernPlugin.definition.function.description).toBeTruthy();
      expect(barnsleyFernPlugin.definition.function.description.toLowerCase()).toContain("barnsley");
    });

    it("should have parameter schema", () => {
      expect(barnsleyFernPlugin.definition.function.parameters).toBeDefined();
      expect(barnsleyFernPlugin.definition.function.parameters).toBeDefined();
    });
  });

  describe("IFS Properties", () => {
    it("should generate points within expected bounds", async () => {
      const result = await barnsleyFernPlugin.execute({ points: 1000 });
      
      const boundsMatch = result.match(/X\[(-?\d+\.\d+), (-?\d+\.\d+)\] Y\[(-?\d+\.\d+), (\d+\.\d+)\]/);
      expect(boundsMatch).toBeTruthy();
      
      if (boundsMatch) {
        const xMin = parseFloat(boundsMatch[1]!);
        const xMax = parseFloat(boundsMatch[2]!);
        const yMin = parseFloat(boundsMatch[3]!);
        const yMax = parseFloat(boundsMatch[4]!);
        
        expect(xMin).toBeGreaterThan(-3);
        expect(xMax).toBeLessThan(3);
        expect(yMin).toBeGreaterThan(-1);
        expect(yMax).toBeLessThan(12);
      }
    });

    it("should render with different symbols", async () => {
      const symbols = ['@', '#', '*', '+', 'F'];
      
      for (const sym of symbols) {
        const result = await barnsleyFernPlugin.execute({ 
          points: 500,
          symbol: sym
        });
        expect(result).toContain(sym);
      }
    });
  });

  describe("Error Handling", () => {
    it("should handle zero points", async () => {
      const result = await barnsleyFernPlugin.execute({ points: 0 });
      expect(result).toContain("Barnsley Fern");
    });

    it("should handle negative point count", async () => {
      const result = await barnsleyFernPlugin.execute({ points: -100 });
      expect(result).toContain("Barnsley Fern");
    });

    it("should handle very small canvas", async () => {
      const result = await barnsleyFernPlugin.execute({ 
        width: 1, 
        height: 1,
        points: 100
      });
      expect(result).toContain("Barnsley Fern");
    });
  });
});
