import { describe, it, expect } from "vitest";
import { 
  expandLSystem, 
  generateLSystemOutput, 
  pointsToAscii,
  runLSystem,
  PRESETS 
} from "./lindenmayer";

describe("Lindenmayer Plugin", () => {
  describe("expandLSystem", () => {
    it("should expand simple axiom without rules", () => {
      const result = expandLSystem("F", {}, 3);
      expect(result).toBe("F");
    });

    it("should expand once with simple rule", () => {
      const result = expandLSystem("F", { F: "FG" }, 1);
      expect(result).toBe("FG");
    });

    it("should expand multiple times", () => {
      const result = expandLSystem("F", { F: "FF" }, 3);
      expect(result).toBe("FFFFFFFF");
    });

    it("should apply rules left-to-right in single pass", () => {
      // After 1 iteration: X -> F[+X]F[-X], and the F characters stay as F
      const result = expandLSystem("X", { X: "F[+X]F[-X]", F: "FF" }, 1);
      expect(result).toBe("F[+X]F[-X]"); // Rules apply once per iteration
    });

    it("should handle second iteration with multiple rules", () => {
      // After 2 iterations: X and all F from first iteration get replaced
      const result = expandLSystem("X", { X: "F[+X]F[-X]", F: "FF" }, 2);
      // Each F becomes FF, X becomes F[+X]F[-X]
      expect(result).toBe("FF[+F[+X]F[-X]]FF[-F[+X]F[-X]]");
    });
  });

  describe("generateLSystemOutput", () => {
    it("should generate points for simple line", () => {
      const result = generateLSystemOutput("F", 90, 1);
      expect(result.points.length).toBeGreaterThan(0);
      expect(result.points).toHaveLength(2);
    });

    it("should track bounds", () => {
      const result = generateLSystemOutput("FFF", 90, 1);
      expect(result.maxY).toBeGreaterThan(result.minY);
    });

    it("should handle push/pop operations", () => {
      const result = generateLSystemOutput("F[+F]F", 90, 1);
      expect(result.points.length).toBeGreaterThan(2);
    });

    it("should handle turns", () => {
      const result = generateLSystemOutput("F+F-F", 90, 1);
      expect(result.points.length).toBeGreaterThan(2);
    });
  });

  describe("pointsToAscii", () => {
    it("should handle empty points", () => {
      const result = pointsToAscii([]);
      expect(result).toBe("Empty L-System");
    });

    it("should render horizontal line", () => {
      const points: [number, number][] = [[0, 0], [10, 0]];
      const result = pointsToAscii(points, 20, 10);
      expect(result).toContain(".");
    });
  });

  describe("runLSystem", () => {
    it("should run predefined plant preset", () => {
      const result = runLSystem("plant");
      expect(result).toContain("Bushy Plant");
      expect(result).toContain("Symbols:");
      expect(result).toContain("Generated by Lindenmayer");
    });

    it("should handle unknown preset", () => {
      const result = runLSystem("nonexistent");
      expect(result).toContain("Unknown preset");
      expect(result).toContain("Available presets");
    });

    it("should list available presets in error", () => {
      const result = runLSystem("xyz");
      Object.keys(PRESETS).forEach(key => {
        expect(result.toLowerCase()).toContain(key.toLowerCase());
      });
    });
  });

  describe("PRESETS", () => {
    it("should have dragon preset with X in axiom", () => {
      expect(PRESETS.dragon!.config.axiom).toContain("X");
    });

    it("should have sierpinski with 120 degree angle", () => {
      expect(PRESETS.sierpinski!.config.angle).toBe(120);
    });

    it("should have binary preset with moderate iterations", () => {
      expect(PRESETS.binary!.config.iterations).toBeLessThan(10);
    });

    it("should have koch with F containing + in rules", () => {
      expect(PRESETS.koch!.config.rules.F).toContain("+");
    });

    it("should have plant preset with 25 degree angle", () => {
      expect(PRESETS.plant!.config.angle).toBe(25);
    });

    it("should have koch3d preset with brackets", () => {
      expect(PRESETS.koch3d!.config.rules.F).toContain("[");
    });
  });
});
