import { describe, it, expect } from "vitest";
import { mandelbrotPlugin } from "./mandelbrot";

describe("Mandelbrot Plugin", () => {
  describe("parameter validation", () => {
    it("should clamp width to valid range", () => {
      const result = mandelbrotPlugin.execute({ width: 300 });
      expect(result).toContain("size=200x");
    });

    it("should clamp height to valid range", () => {
      const result = mandelbrotPlugin.execute({ height: 200 });
      expect(result).toContain("x100");
    });

    it("should clamp iterations to valid range", () => {
      const result = mandelbrotPlugin.execute({ iterations: 10000 });
      expect(result).toContain("iterations=5000");
    });

    it("should use default parameters", () => {
      const result = mandelbrotPlugin.execute({});
      expect(result).toContain("size=80x40");
      expect(result).toContain("iterations=100");
      expect(result).toContain("center=(-0.5, 0)");
    });

    it("should accept custom center point", () => {
      const result = mandelbrotPlugin.execute({ center: [0, -1] });
      expect(result).toContain("center=(0, -1)");
    });

    it("should accept zoom parameter", () => {
      const result = mandelbrotPlugin.execute({ zoom: 10 });
      expect(result).toContain("zoom=10");
    });
  });

  describe("output format", () => {
    it("should generate header with parameters", () => {
      const result = mandelbrotPlugin.execute({});
      expect(result).toContain("=== Mandelbrot Set ===");
      expect(result).toContain("Parameters:");
      expect(result).toContain("Points:");
      expect(result).toContain("Generated by Daedalus");
    });

    it("should contain timing information", () => {
      const result = mandelbrotPlugin.execute({});
      expect(result).toMatch(/render: \d+ms/);
    });
  });

  describe("fractal properties", () => {
    it("should always contain some max-iter points (mandelbrot interior)", () => {
      const result = mandelbrotPlugin.execute({ width: 40, height: 20, iterations: 50 });
      expect(result).toContain("escape iterations:");
    });

    it("should show higher detail with more iterations", () => {
      const result1 = mandelbrotPlugin.execute({ width: 20, height: 10, iterations: 10 });
      const result2 = mandelbrotPlugin.execute({ width: 20, height: 10, iterations: 100 });
      // More iterations should take longer, but just verify both work
      expect(result1).toContain("Mandelbrot Set");
      expect(result2).toContain("Mandelbrot Set");
    });

    it("zoomed view should have different escape distribution", () => {
      const base = mandelbrotPlugin.execute({ width: 20, height: 10, zoom: 1 });
      const zoomed = mandelbrotPlugin.execute({ width: 20, height: 10, zoom: 100 });
      // Both should successfully render
      expect(base).toContain("Mandelbrot Set");
      expect(zoomed).toContain("Mandelbrot Set");
      expect(zoomed).toContain("zoom=100");
    });
  });

  describe("edge cases", () => {
    it("should handle very small size", () => {
      const result = mandelbrotPlugin.execute({ width: 1, height: 1 });
      expect(result).toContain("Mandelbrot Set");
    });

    it("should handle minimum iterations", () => {
      const result = mandelbrotPlugin.execute({ iterations: 1 });
      expect(result).toContain("escape iterations:");
    });

    it("should handle extreme zoom", () => {
      const result = mandelbrotPlugin.execute({ zoom: 10000 });
      expect(result).toContain("zoom=10000");
    });
  });

  describe("definition", () => {
    it("should have correct name", () => {
      expect(mandelbrotPlugin.definition.function.name).toBe("mandelbrot");
    });

    it("should have type function", () => {
      expect(mandelbrotPlugin.definition.type).toBe("function");
    });

    it("should have all expected properties", () => {
      const props = (mandelbrotPlugin.definition.function.parameters as any)?.properties as Record<string, any>;
      expect(props).toHaveProperty("width");
      expect(props).toHaveProperty("height");
      expect(props).toHaveProperty("iterations");
      expect(props).toHaveProperty("center");
      expect(props).toHaveProperty("zoom");
    });
  });
});
